### PR TITLE
fix: use default value for minZoom if not defined

### LINKED ISSUE #995: Map minimum zoom is not properly initialized
If no minZoom is given to the map, it is not possible to zoom in on the map.

### PR DESCRIPTION
**Pull request by QuCMGisaia**
- Fix #995

### CODE REVIEW

**Review by MohamedHamouGisaia — APPROVED** [review]

File: projects/arlas-map/src/lib/arlas-map.component.ts [hunk 1]
```diff
@@ -267,9 +267,8 @@ export class ArlasMapComponent<L, S, M> {
     if (this.maxZoom === undefined || this.maxZoom === null) {
```
Comment (sebbousquet) [inline projects/arlas-map/src/lib/arlas-map.component.ts:267]: Not doing the same test for maxZoom ?

**Review by sebbousquet — APPROVED** [review]
