### PR TITLE
Fix count values in legend

### LINKED ISSUE #673: layers displaying not normalized count have wrong legends
The legend shows NaN

### PR DESCRIPTION
**Pull request by MohamedHamouGisaia**
- Fix #673

### CODE REVIEW

File: projects/arlas-components/src/lib/components/mapgl-legend/mapgl-legend.component.ts [hunk 1]
```diff
@@ -329,7 +329,12 @@ export class MapglLegendComponent implements OnInit, AfterViewInit, OnChanges {
           const maximum = palette.slice(-1)[0].proportion;
           palette.forEach(c => colorLegend.interpolatedValues.push(c.value));
           const colorValues = colorExpression.filter((c, i) => i > 2 && i % 2 !== 0);
-          if (legendData && legendData.get(field)) {
+          console.log('field : ' + field);
+          console.log('legend data : ');
+          console.log(legendData);
+          console.log('color values');
+          console.log(colorValues);
```
Comment (sebbousquet) [inline projects/arlas-components/src/lib/components/mapgl-legend/mapgl-legend.component.ts:336]: 🙈

Comment (MohamedHamouGisaia) [reply projects/arlas-components/src/lib/components/mapgl-legend/mapgl-legend.component.ts]: fixed :1st_place_medal:

**Review by sebbousquet — APPROVED** [review]
